[build]
  command = "npm run build"
  publish = "dist"

# SPA fallback (prevents blank page / 404 on refresh)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: cache headers for static assets (tweak path to your assets folder as needed)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"
